CREATE TABLE IF NOT EXISTS `scrap_applications` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `scrap_number` varchar(50) NOT NULL COMMENT '报废申请编号',
  `device_id` int(11) NOT NULL COMMENT '设备ID',
  `reason_type` enum('damage','obsolete','expired','other') NOT NULL COMMENT '报废原因类型',
  `description` text COMMENT '详细说明',
  `images` json DEFAULT NULL COMMENT '报废图片 URL 列表',
  `estimated_loss` decimal(10,2) DEFAULT 0.00 COMMENT '预估损失金额',
  `actual_loss` decimal(10,2) DEFAULT 0.00 COMMENT '实际损失金额',
  `applicant_id` int(11) NOT NULL COMMENT '申请人ID',
  `status` enum('pending','approved','rejected','completed') NOT NULL DEFAULT 'pending' COMMENT '状态',
  `approved_by` int(11) DEFAULT NULL COMMENT '审核人ID',
  `approved_at` datetime DEFAULT NULL COMMENT '审核时间',
  `approval_notes` text COMMENT '审核备注',
  `processed_by` int(11) DEFAULT NULL COMMENT '处理人ID',
  `processed_at` datetime DEFAULT NULL COMMENT '处理时间',
  `processing_notes` text COMMENT '处理备注',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL COMMENT '更新时间',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scrap_number` (`scrap_number`),
  KEY `idx_device_id` (`device_id`),
  KEY `idx_applicant_id` (`applicant_id`),
  KEY `idx_status` (`status`),
  KEY `idx_reason_type` (`reason_type`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='报废申请表';