package openapi

import (
	"fmt"
	"go/ast"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// schemaBuilder 保存构建 OpenAPI 规范时的状态，
// 包括组件 schema 以及所有已解析结构体 AST 的映射。
type schemaBuilder struct {
	spec       *openapi3.T
	allStructs map[string]*ast.StructType
}

// BuildSpec 基于解析出的 API 定义构建完整的 OpenAPI v3 规范。
func BuildSpec(apiDefs []APIDefinition, projectName string, allStructs map[string]*ast.StructType) (*openapi3.T, error) {
	spec := &openapi3.T{
		OpenAPI: "3.0.0",
		Info: &openapi3.Info{
			Title:       fmt.Sprintf("%s API", projectName),
			Version:     "1.0.0",
			Description: "API documentation generated by Maltose.",
		},
		Paths:      openapi3.NewPaths(),
		Components: &openapi3.Components{},
	}
	spec.Components.Schemas = make(openapi3.Schemas)

	builder := &schemaBuilder{
		spec:       spec,
		allStructs: allStructs,
	}

	for _, apiDef := range apiDefs {
		if apiDef.Path == "" {
			continue
		}
		method := strings.ToUpper(apiDef.Method)
		if method != "GET" && method != "POST" && method != "PUT" && method != "DELETE" {
			return nil, fmt.Errorf("unsupported HTTP method %q for path %s", apiDef.Method, apiDef.Path)
		}

		pathItem := spec.Paths.Find(apiDef.Path)
		if pathItem == nil {
			pathItem = &openapi3.PathItem{}
			spec.Paths.Set(apiDef.Path, pathItem)
		}

		op := &openapi3.Operation{
			Tags:        []string{apiDef.Tag},
			Summary:     apiDef.Summary,
			Description: apiDef.Description,
			Responses:   openapi3.NewResponses(),
		}

		// 处理请求
		if method == "GET" {
			for _, field := range apiDef.Request.Fields {
				paramSchema := builder.typeToSchemaRef(field.Type).Value // 解包 SchemaRef 以用于参数
				param := openapi3.NewQueryParameter(field.JSONName).
					WithDescription(field.Description).
					WithRequired(field.Required).
					WithSchema(paramSchema)
				op.Parameters = append(op.Parameters, &openapi3.ParameterRef{
					Value: param,
				})
			}
		} else { // POST、PUT、DELETE 等
			reqSchema := openapi3.NewObjectSchema()
			for _, field := range apiDef.Request.Fields {
				fieldSchemaRef := builder.typeToSchemaRef(field.Type)
				if field.Description != "" && fieldSchemaRef.Value != nil {
					fieldSchemaRef.Value.Description = field.Description
				}
				reqSchema.Properties[field.JSONName] = fieldSchemaRef
				if field.Required {
					reqSchema.Required = append(reqSchema.Required, field.JSONName)
				}
			}
			op.RequestBody = &openapi3.RequestBodyRef{
				Value: openapi3.NewRequestBody().
					WithDescription(apiDef.Request.Name).
					WithContent(openapi3.NewContentWithJSONSchemaRef(&openapi3.SchemaRef{Value: reqSchema})),
			}
		}

		// 处理响应
		resSchema := openapi3.NewObjectSchema()
		for _, field := range apiDef.Response.Fields {
			fieldSchemaRef := builder.typeToSchemaRef(field.Type)
			if field.Description != "" && fieldSchemaRef.Value != nil {
				fieldSchemaRef.Value.Description = field.Description
			}
			resSchema.Properties[field.JSONName] = fieldSchemaRef
		}
		op.Responses.Set("200", &openapi3.ResponseRef{
			Value: openapi3.NewResponse().
				WithDescription("Success").
				WithContent(openapi3.NewContentWithJSONSchemaRef(&openapi3.SchemaRef{Value: resSchema})),
		})

		// 将操作绑定到路径项
		switch method {
		case "GET":
			if pathItem.Get != nil {
				return nil, fmt.Errorf("duplicate GET operation for path %s", apiDef.Path)
			}
			pathItem.Get = op
		case "POST":
			if pathItem.Post != nil {
				return nil, fmt.Errorf("duplicate POST operation for path %s", apiDef.Path)
			}
			pathItem.Post = op
		case "PUT":
			if pathItem.Put != nil {
				return nil, fmt.Errorf("duplicate PUT operation for path %s", apiDef.Path)
			}
			pathItem.Put = op
		case "DELETE":
			if pathItem.Delete != nil {
				return nil, fmt.Errorf("duplicate DELETE operation for path %s", apiDef.Path)
			}
			pathItem.Delete = op
		}
	}

	return spec, nil
}

// typeToSchemaRef 将 Go 类型字符串转换为 OpenAPI SchemaRef。
// 支持基础类型、指针、切片，并为自定义结构体生成组件 schema。
func (b *schemaBuilder) typeToSchemaRef(goType string) *openapi3.SchemaRef {
	// 处理指针
	if strings.HasPrefix(goType, "*") {
		ref := b.typeToSchemaRef(strings.TrimPrefix(goType, "*"))
		// 若指向的是组件引用，则组件本身不可为 null，可为 null 的是该引用。
			// 若是内联 schema，则可以设置 nullable。
		if ref.Value != nil {
			ref.Value.Nullable = true
		}
		return ref
	}

	// 处理切片/数组
	if strings.HasPrefix(goType, "[]") {
		innerType := strings.TrimPrefix(goType, "[]")
		itemsRef := b.typeToSchemaRef(innerType)
		schema := openapi3.NewArraySchema()
		schema.Items = itemsRef
		return &openapi3.SchemaRef{Value: schema}
	}

	// 处理基础类型
	switch goType {
	case "string":
		return &openapi3.SchemaRef{Value: openapi3.NewStringSchema()}
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64":
		return &openapi3.SchemaRef{Value: openapi3.NewIntegerSchema()}
	case "float32", "float64":
		return &openapi3.SchemaRef{Value: openapi3.NewFloat64Schema()}
	case "bool":
		return &openapi3.SchemaRef{Value: openapi3.NewBoolSchema()}
	case "interface{}":
		return &openapi3.SchemaRef{Value: &openapi3.Schema{Type: &openapi3.Types{openapi3.TypeObject}, AdditionalProperties: openapi3.AdditionalProperties{Has: openapi3.BoolPtr(true)}}}
	}

	// 处理自定义结构体类型：为其创建组件 schema
	cleanTypeName := goType
	if i := strings.LastIndex(goType, "."); i != -1 {
		cleanTypeName = goType[i+1:]
	}

	// 若组件中尚不存在该 schema，则创建它。
	if _, ok := b.spec.Components.Schemas[cleanTypeName]; !ok {
		structAST, found := b.allStructs[cleanTypeName]
		if !found {
			// 未找到结构体定义时，兜底返回一个通用 object schema。
			schema := openapi3.NewObjectSchema()
			schema.Description = "Unresolved custom type: " + goType
			return &openapi3.SchemaRef{Value: schema}
		}

		// 先在组件中放入占位 schema，避免自引用结构体导致无限递归。
		b.spec.Components.Schemas[cleanTypeName] = &openapi3.SchemaRef{Value: openapi3.NewObjectSchema()}

		// 构建结构体的完整 schema。
		schema := openapi3.NewObjectSchema()
		structInfo := parseStructInfo(cleanTypeName, structAST, "POST") // 使用 "POST" 以优先采用 `json` 标签。
		for _, field := range structInfo.Fields {
			fieldSchemaRef := b.typeToSchemaRef(field.Type)
			if field.Description != "" && fieldSchemaRef.Value != nil {
				fieldSchemaRef.Value.Description = field.Description
			}
			schema.Properties[field.JSONName] = fieldSchemaRef
			if field.Required {
				schema.Required = append(schema.Required, field.JSONName)
			}
		}

		// 用构建完成的 schema 替换占位。
		b.spec.Components.Schemas[cleanTypeName] = &openapi3.SchemaRef{Value: schema}
	}

	// 返回指向该组件 schema 的引用。
	return openapi3.NewSchemaRef(fmt.Sprintf("#/components/schemas/%s", cleanTypeName), nil)
}
